services:
  - type: web
    name: reconova-api
    runtime: node
    region: singapore
    buildCommand: npm install && npm run build && npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: NODE_ENV
        value: production
